Update to icedtea-2.6pre06.
PR1903: [REGRESSION] Bug reports now lack IcedTea version & distribution packaging information
S7047033: (smartcardio) Card.disconnect(boolean reset) does not reset when reset is true
S7090324: gclog rotation via external tool
S7094099: DropDown List of JComboBox detached
S7121403: [TESTBUG] runtime/7051189/Xchecksig.sh fails on 64bit solaris
S7130140: using horizontal scroll button on mouse causes a message to be printed on stdout
S7153157: ClassValue.get does not return if computeValue calls remove
S7160604: Using non-opaque windows - popups are initially not painted correctly
S7164841: Improvements to the GC log file rotation
S7172865: PropertyDescriptor fails to work with setter method name if setter is non-void
S7195480: javax.smartcardio does not detect cards on Mac OS X
S8010738: G1: Output for full GCs with +PrintGCDetails should contain perm gen/meta data size change info
S8011795: DOM Serializer prints stack traces to System.err
S8013098: [macosx] localized aqua_xx.properties are not included in rt.jar
S8022070: Compilation error in stubGenerator_sparc.cpp with some compilers
S8024061: Exception thrown when drag and drop between two components is executed quickly
S8024677: [TESTBUG] Move tests for classes in /testlibrary
S8024932: [TEST_BUG] [macosx] javax/swing/text/StyledEditorKit/8016833/bug8016833.java failed
S8025710: Proxied HTTPS connections reused by HttpClient can send CONNECT to the server
S8026792: HOTSPOT: licensee reports a JDK8 build failure after 8005849/8005008 fixes integrated.
S8028192: Use of PKCS11-NSS provider in FIPS mode broken
S8028617: Dvorak keyboard mapping not honored when ctrl key pressed
S8028627: Unsynchronized code path from javax.crypto.Cipher to the WeakHashMap used by JceSecurity to store codebase mappings
S8028726: (prefs) Check src/solaris/native/java/util/FileSystemPreferences.c for JNI pending exceptions
S8030114: [parfait] warnings from b119 for jdk.src.share.native.sun.security.smartcardio: JNI exception pending
S8031075: [Regression] focus disappears with shift+tab on dialog having one focus component
S8032788: ImageIcon constructor throws an NPE and hangs when passed a null String parameter
S8032874: ArrayIndexOutOfBoundsException in JTable while clearing data in JTable
S8033113: wsimport fails on WSDL:header parameter name customization
S8033571: [parfait] warning from b128 for security/smartcardio/pcsc_md.c: JNI exception pending
S8033696: "assert(thread != NULL) failed: just checking" due to Thread::current() and JNI pthread interaction
S8034118: [parfait] JNI exception pending in macosx/native/sun/awt/JavaComponentAccessibility.m
S8034200: Test java/net/CookieHandler/LocalHostCookie.java fails after fix of JDK-7169142
S8034768: [parfait] JNI exception pending in jdk/src/macosx/native/sun/awt/JavaTextAccessibility.m
S8036819: JAB: mneumonics not read for textboxes
S8036861: Application can't be loaded fine,the save dialog can't show up.
S8036983: JAB:Multiselection Ctrl+CursorUp/Down and ActivateDescenderPropertyChanged event
S8037477: Reproducible hang of JAWS and webstart application with JAB 2.0.4
S8037945: Paths.get("").normalize() throws ArrayIndexOutOfBoundsException
S8038000: java.awt.image.RasterFormatException: Incorrect scanline stride
S8038306: (tz) Support tzdata2014b
S8038440: backport few C2 fixes
S8038925: Java with G1 crashes in dump_instance_fields using jmap or jcmd without fullgc
S8038961: kinit, klist and ktab aren't built from jdk7u51 in licensee src bundles
S8039042: G1: Phantom zeros in cardtable
S8039050: Crash in C2 compiler at Node::rematerialize
S8039097: Some tests fail with NPE since 7u60 b12
S8039118: Windows build failure (j2pcsc.dll : fatal error unresolved external symbol throwByName)
S8039292: new hotspot build - hs24.80-b07
S8039298: assert(base == NULL || t_adr->isa_rawptr() || ! phase->type(base)->higher_equal(TypePtr::NULL_PTR))
S8039319: (smartcardio) Card.transmitControlCommand() does not work on Mac OS X
S8039368: Remove testcase from npt utf.c
S8039396: NPE when writing a class descriptor object to a custom ObjectOutputStream
S8039891: Remove ppcsflt builds from JPRT
S8039899: Missing licence headers in test for JDK-8033113
S8040664: Revert temporary fix JDK-8038785
S8040790: [TEST_BUG] tools/javac/innerClassFile/Driver.sh fails to cleanup files after it
S8041351: Crash in src/share/vm/opto/loopnode.cpp:3215 - assert(! had_error) failed: bad dominance
S8041451: com.sun.jndi.ldap.Connection:ReadTimeout should abandon ldap request
S8041507: Java Access Bridge version strings need to be fixed
S8041725: Nimbus JList selection colors persist across L&F changes
S8041931: test/sun/net/www/http/HttpClient/B8025710.java fails with cannot find keystore
S8042059: Various fixes to linux/sparc
S8042247: Make 7u60 the default jprt release for hs24.80
S8042250: Misleading command line output for ReservedCodeCacheSize validation
S8042857: 14 stuck threads waiting for notification on LDAPRequest
S8043012: (tz) Support tzdata2014c
S8043205: Incorrect system traps.h include path
S8043207: Add const to Address argument for Assembler::swap
S8043210: Add _BIG_ENDIAN define on linux/sparc
S8043507: javax.smartcardio.CardTerminals.list() fails on MacOSX
S8043720: (smartcardio) Native memory should be handled more accurately
S8050942: PPC64: implement template interpreter for ppc64le
S8050972: Concurrency problem in PcDesc cache
Adapt AIX port to 5049299: (process) Use posix_spawn, not fork, on S10 to avoid swap exhaustion
Adapt aix to 8022507
Fix aix after 8022507: SIGSEGV at ParMarkBitMap::verify_clear()

2014-08-13  Andrew John Hughes  <gnu.andrew@member.fsf.org>

	* Makefile.am,
	(JDK_UPDATE_VERSION): Set to 80.
	(BUILD_VERSION): Set to b01.
	(CORBA_CHANGESET): Update to icedtea-2.6pre06.
	(JAXP_CHANGESET): Likewise.
	(JAXWS_CHANGESET): Likewise.
	(JDK_CHANGESET): Likewise.
	(LANGTOOLS_CHANGESET): Likewise.
	(OPENJDK_CHANGESET): Likewise.
	(CORBA_SHA256SUM): Likewise.
	(JAXP_SHA256SUM): Likewise.
	(JAXWS_SHA256SUM): Likewise.
	(JDK_SHA256SUM): Likewise.
	(LANGTOOLS_SHA256SUM): Likewise.
	(OPENJDK_SHA256SUM): Likewise.
	* NEWS: Updated.
	* configure.ac: Bump to 2.6pre06.
	* hotspot.map: Update to icedtea-2.6pre06.
	* patches/boot/ecj-diamond.patch: Add new
	case introduced in java.beans.MethodRef.
	* patches/boot/ecj-multicatch.patch:
	Regenerated.