Bump to icedtea-2.6pre09.
PR2003: --disable-system-gtk option broken by refactoring in PR1736
PR2009: Checksum of policy JAR files changes on every build
PR2025: LCMS_CFLAGS & LCMS_LIBS should not be used unless SYSTEM_LCMS is enabled
RH1015432: java-1.7.0-openjdk: Fails on PPC with StackOverflowError (revised comprehensive fix)
S4792059: test/java/io/pathNames/GeneralSolaris.java fails on symbolic links
S6545422: [TESTBUG] NativeErrors.java uses wrong path name in exec
S6642881: Improve performance of Class.getClassLoader()
S6653795: C2 intrinsic for Unsafe.getAddress performs pointer sign extension on 32-bit systems
S6883953: java -client -XX:ValueMapInitialSize=0 crashes
S7010989: Duplicate closure of file descriptors leads to unexpected and incorrect closure of sockets
S7047033: (smartcardio) Card.disconnect(boolean reset) does not reset when reset is true
S7058832: com/sun/net/httpserver/bugs/B6373555.java failing intermittently
S7087021: TEST: com/sun/crypto/provider/Mac/MacClone.java failed on Solaris sparc 5.10
S7122142: (ann) Race condition between isAnnotationPresent and getAnnotations
S7142035: assert in j.l.instrument agents during shutdown when daemon thread is running
S7158636: InterfaceAddress.getBroadcast() returns invalid broadcast address on WLAN
S7160837: DigestOutputStream does not turn off digest calculation when "close()" is called
S7169142: CookieHandler does not work with localhost
S7185456: (ann) Optimize Annotation handling in java/sun.reflect.* code for small number of annotations
S7195480: javax.smartcardio does not detect cards on Mac OS X
S7197159: accept different kvno if there no match
S8001105: findVirtual of Object[].clone produces internal error
S8001108: an attempt to use "<init>" as a method name should elicit NoSuchMethodException
S8001109: arity mismatch on a call to spreader method handle should elicit IllegalArgumentException
S8001472: api/java_awt/Window/indexTGF_* tests fail because expected colors aren't equal
S8005232: (JEP-149) Class Instance size reduction
S8009258: TEST_BUG:java/io/pathNames/GeneralWin32.java fails intermittently
S8011646: SEGV in compiled code with loop predication
S8012026: [macosx] Component.getMousePosition() does not work in an applet on MacOS
S8012625: Incorrect handling of HTTP/1.1 " Expect: 100-continue " in HttpURLConnection
S8012637: Adjust CipherInputStream class to work in AEAD/GCM mode
S8012941: JSR 292: too deep inlining might crash compiler because of stack overflow
S8013836: getFirstDayOfWeek reports wrong day for pt-BR locale
S8015256: Better class accessibility
S8015421: NegativeArraySizeException occurs in ChunkedOutputStream() with Integer.MAX_VALUE
S8015586: [macosx] Test closed/java/awt/print/PrinterJob/PrintToDir.java fails on MacOSX
S8015628: Test Failure in closed/java/io/pathNames/GeneralSolaris.java
S8016545: java.beans.XMLEncoder.writeObject output is wrong
S8017212: File.createTempFile requires unnecessary "read" permission
S8019324: assert(_f2 == 0 || _f2 == f2) failed: illegal field change
S8019623: Lack of synchronization in AppContext.getAppContext()
S8021372: NetworkInterface.getNetworkInterfaces() returns duplicate hardware address
S8021804: Certpath validation fails if validity period of root cert does not include validity period of intermediate cert
S8022070: Compilation error in stubGenerator_sparc.cpp with some compilers
S8022229: Intermittent test failures in sun/tools/jstatd
S8022721: TEST_BUG: AnnotationTypeDeadlockTest.java throws java.lang.IllegalStateException: unexpected condition
S8022783: Optimize C2 optimizations
S8024061: Exception thrown when drag and drop between two components is executed quickly
S8024283: 10 nashorn tests fail with similar stack trace InternalError with cause being NoClassDefFoundError
S8024616: JSR292: lazily initialize core NamedFunctions used for bootstrapping
S8025051: Update resource files for TimeZone display names
S8025644: java/util/stream/test/org/openjdk/tests/java/util/stream/ToArrayOpTest.java fails with TestData): failure java.lang.AssertionError: expected [true] but found [false]
S8025917: JDK demo applets not running with >=7u40 or (JDK 8 and JDK 9)
S8026792: HOTSPOT: licensee reports a JDK8 build failure after 8005849/8005008 fixes integrated.
S8027359: XML parser returns incorrect parsing results
S8028159: C2: compiler stack overflow during inlining of @ForceInline methods
S8028192: Use of PKCS11-NSS provider in FIPS mode broken
S8028280: ParkEvent leak when running modified runThese which only loads classes
S8028616: Htmleditorkit parser doesn't handle leading slash (/)
S8028617: Dvorak keyboard mapping not honored when ctrl key pressed
S8028623: SA: hash codes in SymbolTable mismatching java_lang_String::hash_code for extended characters.
S8028627: Unsynchronized code path from javax.crypto.Cipher to the WeakHashMap used by JceSecurity to store codebase mappings
S8028631: Improve the test coverage to the pathname handling on unix-like platforms
S8028726: (prefs) Check src/solaris/native/java/util/FileSystemPreferences.c for JNI pending exceptions
S8029153: [TESTBUG] test/compiler/7141637/SpreadNullArg.java fails because it expects NullPointerException
S8029190: VM_Version::determine_features() asserts on Fujitsu Sparc64 CPUs
S8029302: Performance regression in Math.pow intrinsic
S8029607: Type of Service (TOS) cannot be set in IPv6 header
S8029837: NPE seen in XMLDocumentFragmentScannerImpl.setProperty since 7u40b33
S8031290: Adjust call to getisax() for additional words returned
S8031502: JSR292: IncompatibleClassChangeError in LambdaForm for CharSequence.toString() method handle type converter
S8032078: [macosx] CPlatformWindow.setWindowState throws RuntimeException, if windowState=ICONIFIED|MAXIMIZED_BOTH
S8032585: JSR292: IllegalAccessError when attempting to invoke protected method from different package
S8032669: Mouse release not being delivered to Swing component in 7u45
S8032788: ImageIcon constructor throws an NPE and hangs when passed a null String parameter
S8032808: Support Solaris SO_FLOW_SLA socket option
S8032872: [macosx] Cannot select from JComboBox in a JWindow
S8032874: ArrayIndexOutOfBoundsException in JTable while clearing data in JTable
S8032878: Editable combos in table do not behave as expected
S8032909: XSLT string-length returns incorrect length when string includes complementary chars
S8033113: wsimport fails on WSDL:header parameter name customization
S8033278: Missed access checks for Lookup.unreflect* after 8032585
S8033696: "assert(thread != NULL) failed: just checking" due to Thread::current() and JNI pthread interaction
S8034200: Test java/net/CookieHandler/LocalHostCookie.java fails after fix of JDK-7169142
S8035162: Service printing service
S8035613: With active Securitymanager JAXBContext.newInstance fails
S8035781: Improve equality for annotations
S8036022: D3D: rendering with XOR composite causes InternalError.
S8036709: Java 7 jarsigner displays warning about cert policy tree
S8036805: Correct linker method lookup.
S8036810: Correct linker field lookup
S8036819: JAB: mneumonics not read for textboxes
S8036823: Stack trace sometimes shows 'locked' instead of 'waiting to lock'
S8036861: Application can't be loaded fine,the save dialog can't show up.
S8036863: Update jdk7 testlibrary to match jdk8 in hotspot
S8036936: Use local locales
S8036981: JAXB not preserving formatting for xsd:any Mixed content
S8036983: JAB:Multiselection Ctrl+CursorUp/Down and ActivateDescenderPropertyChanged event
S8037066: Secure transport layer
S8037477: Reproducible hang of JAWS and webstart application with JAB 2.0.4
S8037846: Ensure streaming of input cipher streams
S8038000: java.awt.image.RasterFormatException: Incorrect scanline stride
S8038274: update 8u fix for 8028073 now that 8028280 is backported to 8u
S8038364: Use certificate exceptions correctly
S8038899: Safer safepoints
S8038903: More native monitor monitoring
S8038908: Make Signature more robust
S8038913: Bolster XML support
S8038925: Java with G1 crashes in dump_instance_fields using jmap or jcmd without fullgc
S8039050: Crash in C2 compiler at Node::rematerialize
S8039097: Some tests fail with NPE since 7u60 b12
S8039298: assert(base == NULL || t_adr->isa_rawptr() || ! phase->type(base)->higher_equal(TypePtr::NULL_PTR))
S8039319: (smartcardio) Card.transmitControlCommand() does not work on Mac OS X
S8039396: NPE when writing a class descriptor object to a custom ObjectOutputStream
S8039509: Wrap sockets more thoroughly
S8039520: More atomicity of atomic updates
S8039533: Higher resolution resolvers
S8040168: Set hotspot version to hs24.66 and build to b01 for 7u66
S8040617: [macosx] Large JTable cell results in a OutOfMemoryException
S8041132: Increment hsx 24.66 build to b02 for 7u66-b09
S8041408: Increment hsx 24.55 build to b04 for 7u55-b34
S8041451: com.sun.jndi.ldap.Connection:ReadTimeout should abandon ldap request
S8041529: Better parameterization of parameter lists
S8041540: Better use of pages in font processing
S8041545: Better validation of generated rasters
S8041564: Improved management of logger resources
S8041717: Issue with class file parser
S8041791: String.toLowerCase regression - violates Unicode standard
S8042052: assert(t != NULL) failed: must set before get
S8042059: Various fixes to linux/sparc
S8042582: Test java/awt/KeyboardFocusmanager/ChangeKFMTest/ChangeKFMTest.html fails on Windows x64
S8042590: Running form URL throws NPE
S8042603: 'SafepointPollOffset' was not declared in static member function 'static bool Arguments::check_vm_args_consistency()'
S8042609: Limit splashiness of splash images
S8042797: Avoid strawberries in LogRecord
S8042835: Remove mnemonic character from open, save and open directory JFileChooser's buttons
S8042850: Extra unused entries in ICU ScriptCodes enum
S8042857: 14 stuck threads waiting for notification on LDAPRequest
S8043200: Decrease the preference mode of RC4 in the enabled cipher suite list
S8043205: Incorrect system traps.h include path
S8043206: Fix signed vs. unsigned comparison warning in copy_sparc.hpp
S8043207: Add const to Address argument for Assembler::swap
S8043210: Add _BIG_ENDIAN define on linux/sparc
S8043413: REGRESSION: Hotspot causes segmentation fault in jdk8ux, but not in jdk7ux
S8043507: javax.smartcardio.CardTerminals.list() fails on MacOSX
S8043610: Sorting columns in JFileChooser fails with AppContext NPE
S8044274: Proper property processing
S8044406: JVM crash with JDK8 (build 1.8.0-b132) with G1 GC
S8044602: Increment minor version of HSx for 7u72 and initialize the build number
S8044603: Increment minor version of HSx for 7u71 and initialize the build number
S8044659: Java SecureRandom on SPARC T4 much slower than on x86/Linux
S8044725: Bug in zlib 1.2.5 prevents inflation of some gzipped files (zlib 1.2.8 port)
S8046007: Java app receives javax.print.PrintException: Printer is not accepting job
S8046233: VerifyError on backward branch
S8046287: [TESTBUG] runtime/Thread/TestThreadDumpMonitorContention.java failed error_cnt=12
S8046343: (smartcardio) CardTerminal.connect('direct') does not work on MacOSX
S8046516: Segmentation fault in JVM (easily reproducible)
S8046769: Set T family feature bit on Niagara systems
S8047186: jdk.net.Sockets throws InvocationTargetException instead of original runtime exceptions
S8048080: (smartcardio) javax.smartcardio.Card.openLogicalChannel() dosn't work on MacOSX
S8048110: Using tables in JTextPane leads to infinite loop in FlowLayout.layoutRow
S8048212: Two tests failed with "java.net.SocketException: Bad protocol option" on Windows after 8029607
S8049081: Increment hsx 24.72 build to b02 for 7u72-b03
S8049250: Need a flag to invert the Card.disconnect(reset) argument
S8049343: (tz) Support tzdata2014g
S8049542: C2: assert(size_in_words <= (julong)max_jint) failed: no overflow
S8049684: pstack crashes on java core dump
S8049787: Increment hsx 24.72 build to b03 for 7u72-b04
S8050158: Introduce system property to maintain RC4 preference order
S8050165: linux-sparcv9: NMT detail causes assert((intptr_t*)younger_sp[FP->sp_offset_in_saved_window()] == (intptr_t*)((intptr_t)sp - STACK_BIAS)) failed: younger_sp must be valid
S8050167: linux-sparcv9: hs_err file does not show any stack information
S8050485: super() in a try block in a ctor causes VerifyError
S8051012: Regression in verifier for <init> method call from inside of a branch
S8051359: JPopupMenu creation in headless mode with JDK9b23 causes NPE
S8052162: REGRESSION: sun/java2d/cmm/ColorConvertOp tests fail since 7u71 b01
S8053963: (dc) Use DatagramChannel.receive() instead of read() in connect()
S8054019: Keytool Error publicKey's is not X.509, but X509
S8054530: C2: assert(res == old_res) failed: Inconsistency between old and new
S8054817: File ccache only recognizes Linux and Solaris defaults
S8054883: Segmentation error while running program
S8055176: 7u71 l10n resource file translation update
S8055421: (fs) bad error handling in java.base/unix/native/libnio/fs/UnixNativeDispatcher.c
S8055714: Increment hsx 24.72 build to b04 for 7u72-b11
S8055731: sun/security/smartcardio/TestDirect.java throws java.lang.IndexOutOfBoundsException
S8055949: ByteArrayOutputStream capacity should be maximal array size permitted by VM
S8056156: [TEST_BUG] Test javax/swing/JFileChooser/8046391/bug8046391.java fails in Windows
S8056211: api/java_awt/Event/InputMethodEvent/serial/index.html#Input[serial2002] failure
S8057184: JCK8's api/javax_swing/JDesktopPane/descriptions.html#getset failed with GTKLookAndFeel on Linux and Solaris
S8057564: JVM hangs at getAgentProperties after attaching to VM with lower
S8057813: Alterations to jdk_security3 test target
S8058936: hotspot/test/Makefile should use jtreg script from $JT_HOME/bin/jreg (instead of $JT_HOME/win32/bin/jtreg)

2014-10-16  Andrew John Hughes  <gnu.andrew@member.fsf.org>

	* Makefile.am,
	(CORBA_CHANGESET): Update to icedtea-2.6pre09.
	(JAXP_CHANGESET): Likewise.
	(JAXWS_CHANGESET): Likewise.
	(JDK_CHANGESET): Likewise.
	(LANGTOOLS_CHANGESET): Likewise.
	(OPENJDK_CHANGESET): Likewise.
	(CORBA_SHA256SUM): Likewise.
	(JAXP_SHA256SUM): Likewise.
	(JAXWS_SHA256SUM): Likewise.
	(JDK_SHA256SUM): Likewise.
	(LANGTOOLS_SHA256SUM): Likewise.
	(OPENJDK_SHA256SUM): Likewise.
	* NEWS: Updated.
	* configure.ac: Bump to 2.6.0pre09.
	* hotspot.map.in: Update to icedtea-2.6.0pre09.
	* patches/boot/ecj-diamond.patch:
	Add new cases in javax.swing.JDesktopPane and
	jdk.net.Sockets.
	* patches/boot/ecj-multicatch.patch:
	Add new cases in javax.crypto.CipherInputStream
	and javax.crypto.CipherOutputStream.
	* patches/boot/ecj-stringswitch.patch:
	Add new case in
	sun.reflect.annotation.AnnotationInvocationHandler.